export const GET_RELEASE = 'GET_RELEASES';
export const GET_SINGLE_RELEASE = 'GETTING SINGLE RELEASE';
export const RELEASE_LOADING = 'RELEASE(S) LOADING';
export const GET_RELEASE_ERROR = 'ERROR GETTING RELEASE';
export const CLEAR_RELEASE_ERROR = 'CLEARING RELEASE ERROR';
